
<?php
return [
    "Home",
    "Change Password",
    "Experience the ease and security of our streamlined password change process – regain access to your account in just a few clicks!",
    "Enter your current password",
    "Enter new password",
    "Repeat password",
    "Confirm Password!",
    "Please enter your new password again to confirm and ensure accuracy.",
    "Password",
    "Confirm Password",
    "Forgot Your Password",
    "Recover Password!",
    "Regain access with your seamless and secure account retrieval process in just a few clicks!",
    "Email address",
    "Send Link",
    "Reset Password!",
    "Initiate the password reset process effortlessly and securely to regain control of your account with just a few simple steps.",
    "Confirm New Password",
    "Reset Password",
    "2FA Verification here!",
    "Please enter the verification code to authenticate your identity and proceed with the verification process.",
    "2 FA Code",
    "Submit",
    "Email Verification Here!",
    "Ensure account security with a quick and simple email verification process. Stay protected, stay connected.",
    "Resend code",
    "Phone Number Verify Here!",
    "Validate your phone number effortlessly for enhanced account protection. Verification made simple, security assured.",
    "Google",
    "Facebook",
    "Github",
    "Enter Email or Username",
    "Enter captcha code",
    "Don't have an account?",
    "Create an account",
    "Remember me",
    "Forgot password?",
    "Log In",
    "Username",
    "Confirm Password",
    "Email",
    "Last Name",
    "First Name",
    "Login Here",
    "Don't have an account?",
    "signup",
    "click here to request another",
    "If you did not receive the email",
    "Before proceeding, please check your email for a verification link.",
    "Verify Your Email Address",
    "Back To Home",
    "You don't have permission to access ‘/’ on this server",
    "Forbidden",
    "Page not found!",
    "404",
    "Method Not Allowed",
    "405",
    "Sorry, your session has expired",
    "419",
    "The server encountered an internal error misconfiguration and was unable to complete your request. Please contact the server administrator.",
    "Internal Server Error",
    "Product Details",
    "Quantity",
    "price",
    "Total",
    "Discount:",
    "Your cart total",
    "Subtotal",
    "Discount",
    "Total",
    "Proceed To Checkout",
    "All Type",
    "Sort By",
    "Items found",
    "Categories",
    "Date",
    "Trending",
    "Latest",
    "Popular",
    "Starting-",
    "reviews",
    "Payment",
    "pay securely",
    "Total",
    "Payment Fees",
    "Select",
    "Select Currency",
    "Total Price",
    "Discount",
    "Created",
    "Order Number",
    "Order Summary",
    "Apply",
    "Coupon code",
    "Have a Coupon Code",
    "Others",
    "Related Cards",
    "submit review",
    "Characters remaining",
    "What was your experience?",
    "Review this product",
    "All Reviews",
    "AVG Ratings",
    "Total ReviewsUsers reviews who have purchase",
    "Reviews",
    "Guide",
    "Description",
    "Submit",
    "Description",
    "Amount",
    "Make Offer",
    "make offer",
    "Price: ",
    "(High To Low)",
    "(Low To High)",
    "Price",
    "Search",
    "Search here...",
    "Filter by price",
    "Filters",
    "Pending",
    "Accepted",
    "Rejected",
    "Resubmission",
    "Payment Complete",
    "Payment Processing",
    "Remove",
    "Reject",
    "Accept",
    "Conversation",
    "More",
    "Offer History",
    "Buy",
    "Going to Sell",
    "Post Image ",
    "Make a Offer",
    "Confirmation",
    "Are you confirm to payment now ?",
    "Are you want to reject this offer ?",
    "Reject Offer",
    "Are you want to remove this offer ?",
    "Remove Offer",
    "Say Something",
    "Accept Offer",
    "Make a Offer",
    "Make Offer",
    "Buy Now",
    "Discount",
    "Total price",
    "Important Note",
    "Instant Delivery",
    "Items found",
    "Top Rated",
    "Payment Fees",
    "Payment from your wallet balance",
    "Wallet Payment",
    "How would you like to pay",
    "What was your experience?",
    "Review this product",
    "No Review Found",
    "Reviews About",
    "All",
    "Bad",
    "Poor",
    "Average",
    "Great",
    "Excellent",
    "Avg Rating",
    "Total Reviews",
    "API URL:",
    "HTTP Method:",
    "Base Url",
    "#Get Campaign",
    "Campaign",
    "Response Body",
    "JSON",
    "Response format:",
    "API Key:",
    "id:",
    "name:",
    "start_date:",
    "end_date:",
    "topups:",
    "cards:",
    "campaign id",
    "campaign name",
    "when campaign start",
    "when campaign end",
    "the list of top up services for campaign",
    "the list of card services for campaign",
    "Python",
    "Node.js",
    "Ruby",
    "PHP",
    "cURL",
    "Base Url",
    "To get all the Card list follow the example code and be careful with the parameters.",
    "#Get Cards",
    "The Card Preview Image Url Path",
    "The Card Image Url Path",
    "Card Name",
    "Card Slug",
    "how many active product in category",
    "which type of category, 2 type available top_up,card",
    "category id",
    "category name",
    "category icon",
    "which type of category, 2 type available top_up,card",
    "how many active product in category",
    "Category",
    "#Get Category",
    "To get all the category list follow the example code and be careful with the parameters.",
    "To get all the top up order list follow the example code and be careful with the parameters.",
    "Order List",
    "#Top Up Order List",
    "order_details:",
    "Unique order id",
    "Order total amount",
    "The status of the order. 0=>initiate, 1=>completed,2=>refund,3=>stock_short",
    "Top Up order information",
    "array of object. every service details of order",
    "Top Up",
    "Get Category",
    "Category",
    "Authentication",
    "Introduction",
    "Getting Started",
    "Add Top Up Review",
    "Get Top Up Review",
    "Order Top Up",
    "Get Services By Top Up",
    "Get Top Up Services",
    "Top Up Detail",
    "Get Top By Category",
    "Get Top Ups",
    "Add Card Review",
    "Get Card Review",
    "Order Card",
    "Get Services By Card",
    "Get Card Services",
    "Card Detail",
    "Get Card By Category",
    "Get Cards",
    "Card",
    "Get Campaign",
    "Campaign",
    "Card Order List",
    "Top Up Order List",
    "Order List",
    "The Top Up Preview Image Url Path",
    "The Top Up Image Url Path",
    "Top Up Status. It Should be 1 For All Active Top Up",
    "Top up Slug",
    "Top up Name",
    "Top up Category",
    "Top up id",
    "Manage Payout",
    "Add Fund",
    "Payout Logs",
    "Transactions",
    "Payment Logs",
    "Api Key",
    "Support Ticket",
    "Order List",
    "Sales List",
    "Offer List",
    "Create Sell",
    "Manage Post",
    "Result",
    "Enter search keyword",
    "Sign Out",
    "2 FA Security",
    "Identity Verification",
    "Password Setting",
    "Payout",
    "Dashboard",
    "Refund",
    "Complete",
    "Wait Sending",
    "All Order",
    "Top Up Order",
    "Order List",
    "Offer List",
    "Sales List",
    "Create Sell",
    "Sell Post",
    "Api Key",
    "Support Ticket",
    "Notification Permission",
    "Identity Verification",
    "Password Settings",
    "My Profile",
    "Nightfall",
    "Daybreak",
    "You have ",
    " new notifications",
    "Clear all notification",
    "Accept",
    "Close",
    "By continuing to use our website, you agree to our",
    "Search here...",
    "Login",
    "checkout",
    "View cart",
    " Discount",
    "Subtotal",
    "Products in cart",
    "Select Currency",
    "Select language",
    "Select Language and Currency",
    "save",
    "Sign Up",
    "Welcome to",
    "Log In",
    "Log In/Sign Up",
    "Log In",
    "All Rights Reserved!",
    "Copyright",
    "Address:",
    "Email:",
    "Phone:",
    "Useful Link",
    "Support Link",
    "add fund",
    "How would you like to pay?",
    "cancel",
    "confirm and continue",
    "You send exactly",
    "Funding Amount",
    "Funding Amount",
    "Funding Details",
    "Action",
    "Date",
    "Status",
    "Amount",
    "Method",
    "Transaction ID",
    "Rejected",
    "Pending",
    "Successful",
    "Payment Method",
    "Payment Log Filter",
    "Payment Log Filter",
    "Status",
    "Admin Feedback",
    "Payment Information",
    "New Sell Post",
    "Please Enter",
    "This credentials need for admin approval",
    "How much of this will i earn",
    "Select Category",
    "Category Select",
    "Create New",
    "This Specification need for admin approval",
    "Description",
    "Message to the Reviewer",
    "Add Image",
    "Create",
    "Choose Image",
    "Sell Charge",
    "You will earn",
    "How Much You Earn",
    "Title",
    "Choose Image",
    "Are you sure to delete this?",
    "Yes",
    "Delete Confirm",
    "Update Now",
    "preview image",
    "Comments",
    "How much of this will i earn ?",
    "Edit Sell Post",
    "Sell Posts",
    "Action",
    "Date - Time",
    "No.",
    "Details",
    "Search for Title",
    "Product Name",
    "Sell Post Filter",
    "Off",
    "Transaction Id",
    "Credentials",
    "Card Orders",
    "Search Order",
    "Order Id",
    "Wait Sending",
    "See Codes",
    "Review rating",
    "Pass Codes",
    "Code List",
    "Direct Top Up Orders",
    "Information",
    "SL-",
    "Top Up Information",
    "Game",
    "Added Date",
    "Buy Now",
    "Are you want to remove this game from this collection",
    "Remove Confirmation",
    "Amount In Base Currency",
    "Request Amount",
    "Payout Method",
    "Automatic Payout",
    "Select Bank",
    "Select Transfer",
    "Select Bank Currency",
    "Flutterwave Payout",
    "Choose File",
    "Paystack Payout",
    "Paypal Id",
    "phone",
    "Email",
    "Select Recipient",
    "Select Recipient Type",
    "Request Amount",
    "Charge",
    "Upload Image",
    "Payouts",
    "Detail",
    "Time",
    "Amount (In Base)",
    "Amount",
    "Gateway",
    "Trx ID",
    "Transactions",
    "Pending",
    "Complete",
    "All Payment",
    "Pending Payment",
    "Complete Payment",
    "Rejected Payment",
    "Transaction Filter",
    "Payment Information",
    "Payout",
    "Withdraw processing is off today. Please try",
    "Preferred Payout Method",
    "Waiting for payout preview",
    "Payout Summary",
    "Withdraw",
    "Payout Amount",
    "Amount In",
    "Select Kyc Type",
    "Kyc Type",
    "Verify your process instantly.",
    "KYC Information",
    "Notification Settings",
    "Save Changes",
    "app",
    "sms",
    "browser",
    "email",
    "type",
    "Request Permission",
    "Notification Settings",
    "We need permission from your browser to show notifications.",
    "save changes",
    "Address",
    "Time Zone",
    "Language",
    "Phone Number",
    "Email Address",
    "Username",
    "Your Lastname",
    "Last Name",
    "Your Firstname",
    "First Name",
    "Identity Verification",
    "Notification",
    "profile",
    "History",
    "Identity Verification",
    "Kyc Status",
    "Serial No.",
    "Kyc Type",
    "Approved Date",
    "Submitted Date",
    "Serial",
    "Type",
    "Profile Details",
    "Allowed JPG, GIF or PNG. Max size of 10240Kb",
    "Notification Permissions",
    "Repeat Password",
    "New Password",
    "Enter your current password",
    "Current password",
    "Password Reset",
    "Accept Offer",
    "Remark",
    "Type  user or message",
    "My All Post",
    "Offer List Search",
    "SHOWING ALL",
    "RESULTS",
    "Payment Processing",
    "Price low to high",
    "Price high to low",
    "Latest Offer",
    "Sort By",
    "Offer List",
    "Offer Post",
    "Payment Lock",
    "Are you sure to payment lock for",
    "Payment Lock",
    "Waiting Payment",
    "No specifications available.",
    "Select Payment Currency",
    "Buy now",
    "Enter Your Message",
    "Subject",
    "Enter Subject",
    "Create a new ticket",
    "Ticket Create",
    "Subject",
    "Last Reply",
    "Transaction ID",
    "Closed",
    "Replied",
    "Answered",
    "Open",
    "Transaction ID",
    "Admin",
    "Files",
    "Confirmation !",
    "Transaction Filter",
    "Sell Post",
    "Payout",
    "Order",
    "Deposit",
    "Type",
    "Remark",
    "Confirmation !",
    "Enable Two Factor Authenticator",
    "Two Factor Authenticator",
    "Disable Two Factor Authenticator",
    "Re-generate",
    "2 FA Verification",
    "Download App",
    "Google Authenticator is a multifactor app for mobile devices. It generates timed codes used during the 2-step verification process. To use Google Authenticator, install the Google Authenticator application on your mobile device.",
    "Use Google Authenticator to Scan the QR code  or use the code",
    "Google Authenticator",
    "Are you certain about generating a new API key? If you proceed with generating a new key, the previously used API key may be invalidated or affected. Please confirm before initiating the process to avoid any disruption.",
    "Secret Key:",
    "Public Key:",
    "Copy",
    "Generate Key",
    "Api Key",
    "Reject",
    "Remove",
    "Unknown",
    "view all",
    "Latest offer list",
    "Total Ticket",
    "Main Balance",
    "Card Order",
    "Top Up Order",
    "Slider Image",
    "Method",
    "How much of this will i earn ?",
    "Message to the Reviewer",
    "Sell Post Order",
    "Code List",
    "Direct Top Up Orders",
    "Order Id",
    "Information",
    "Top Up Information",
    "social share :",
    "social share :",
    "Recent Post",
    "WE ARE COMING SOON",
    "stock short",
    "add to cart",
    "Total price",
    "Quantity",
    "stock short",
    "Starting",
    "Denomination",
    "Top Rated",
    "active_children",
    "No results found.",
    "Start typing to search..."
];
